// Execute the actual WorldRasterShaders SPIR-V on Vulkan; verifies depth, cutout and output guides.
#include <vulkan/vulkan.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#define CHECK(x) do { VkResult r=(x);if(r!=VK_SUCCESS){fprintf(stderr,"Vulkan %d line %d\n",r,__LINE__);exit(1);} } while(0)
#define W 16
#define H 16
static VkDevice device;static VkPhysicalDevice physical;
static uint32_t memory_type(uint32_t bits,VkMemoryPropertyFlags flags){VkPhysicalDeviceMemoryProperties p;vkGetPhysicalDeviceMemoryProperties(physical,&p);for(uint32_t i=0;i<p.memoryTypeCount;i++)if((bits&(1u<<i))&&(p.memoryTypes[i].propertyFlags&flags)==flags)return i;fprintf(stderr,"memory type missing\n");exit(1);}
typedef struct {VkBuffer buffer;VkDeviceMemory memory;void *data;VkDeviceSize size;} Buffer;
static Buffer buffer(VkDeviceSize size,VkBufferUsageFlags usage){Buffer b={.size=size};VkBufferCreateInfo ci={.sType=VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,.size=size,.usage=usage,.sharingMode=VK_SHARING_MODE_EXCLUSIVE};CHECK(vkCreateBuffer(device,&ci,NULL,&b.buffer));VkMemoryRequirements req;vkGetBufferMemoryRequirements(device,b.buffer,&req);VkMemoryAllocateInfo ai={.sType=VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,.allocationSize=req.size,.memoryTypeIndex=memory_type(req.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)};CHECK(vkAllocateMemory(device,&ai,NULL,&b.memory));CHECK(vkBindBufferMemory(device,b.buffer,b.memory,0));CHECK(vkMapMemory(device,b.memory,0,size,0,&b.data));memset(b.data,0,size);return b;}
static void free_buffer(Buffer b){vkUnmapMemory(device,b.memory);vkDestroyBuffer(device,b.buffer,NULL);vkFreeMemory(device,b.memory,NULL);}
typedef struct{VkImage image;VkImageView view;VkDeviceMemory memory;} Image;
static Image image(VkFormat format,int depth,int sampled){Image a={0};VkImageCreateInfo ci={.sType=VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,.imageType=VK_IMAGE_TYPE_2D,.format=format,.extent={sampled?1:W,sampled?1:H,1},.mipLevels=1,.arrayLayers=1,.samples=VK_SAMPLE_COUNT_1_BIT,.tiling=VK_IMAGE_TILING_OPTIMAL,.usage=sampled?(VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_TRANSFER_DST_BIT):(depth?VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT:VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT|VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_TRANSFER_DST_BIT|VK_IMAGE_USAGE_SAMPLED_BIT),.sharingMode=VK_SHARING_MODE_EXCLUSIVE};CHECK(vkCreateImage(device,&ci,NULL,&a.image));VkMemoryRequirements req;vkGetImageMemoryRequirements(device,a.image,&req);VkMemoryAllocateInfo ai={.sType=VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,.allocationSize=req.size,.memoryTypeIndex=memory_type(req.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT)};CHECK(vkAllocateMemory(device,&ai,NULL,&a.memory));CHECK(vkBindImageMemory(device,a.image,a.memory,0));VkImageViewCreateInfo vi={.sType=VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,.image=a.image,.viewType=VK_IMAGE_VIEW_TYPE_2D,.format=format,.subresourceRange={.aspectMask=depth?VK_IMAGE_ASPECT_DEPTH_BIT:VK_IMAGE_ASPECT_COLOR_BIT,.levelCount=1,.layerCount=1}};CHECK(vkCreateImageView(device,&vi,NULL,&a.view));return a;}
static void free_image(Image a){vkDestroyImageView(device,a.view,NULL);vkDestroyImage(device,a.image,NULL);vkFreeMemory(device,a.memory,NULL);}
static VkShaderModule shader(const char*path){FILE*f=fopen(path,"rb");if(!f){perror(path);exit(1);}fseek(f,0,SEEK_END);size_t n=ftell(f);rewind(f);void*bytes=malloc(n);if(fread(bytes,1,n,f)!=n)exit(1);fclose(f);VkShaderModuleCreateInfo ci={.sType=VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,.codeSize=n,.pCode=bytes};VkShaderModule m;CHECK(vkCreateShaderModule(device,&ci,NULL,&m));free(bytes);return m;}
static float from_half(uint16_t h){uint32_t s=(h>>15)&1,e=(h>>10)&31,m=h&1023;if(e==0)return (s?-1:1)*ldexpf(m,-24);if(e==31)return m?NAN:(s?-INFINITY:INFINITY);return (s?-1:1)*ldexpf(1+m/1024.0f,(int)e-15);}
// Closed-form roughness=1 isotropic GGX response, independent of shader implementation.
static float expected_color(float albedo,float nv,int channel,const char*mode){
 float metal=strcmp(mode,"metal")==0?1:0,f0=metal?albedo:.04f;
 float fn=f0+(1-f0)*powf(1-nv,5),vh=sqrtf((1+nv)*.5f),fh=f0+(1-f0)*powf(1-vh,5);
 float factor=strcmp(mode,"blocker")==0?0:strcmp(mode,"colored")==0?(channel==0?.5f:channel==1?.25f:.1f):1;
 return (1-metal)*(1-fn)*albedo*(.28f/3.14159265f+factor)+fh/(2*(1+nv))*factor;
}
int main(int argc,char**argv){int shadow_case=argc>3;if(argc!=3&&argc!=4){fprintf(stderr,"usage: %s vert.spv frag.spv [plane|blocker|colored|metal|view]\n",argv[0]);return 2;}
 VkApplicationInfo app={.sType=VK_STRUCTURE_TYPE_APPLICATION_INFO,.pApplicationName="WorldRasterSmoke",.apiVersion=VK_API_VERSION_1_2};VkInstanceCreateInfo ici={.sType=VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,.pApplicationInfo=&app};VkInstance instance;CHECK(vkCreateInstance(&ici,NULL,&instance));uint32_t n=0;CHECK(vkEnumeratePhysicalDevices(instance,&n,NULL));VkPhysicalDevice*all=malloc(n*sizeof(*all));CHECK(vkEnumeratePhysicalDevices(instance,&n,all));physical=all[0];free(all);VkPhysicalDeviceProperties props;vkGetPhysicalDeviceProperties(physical,&props);printf("device: %s\n",props.deviceName);uint32_t qn=0;vkGetPhysicalDeviceQueueFamilyProperties(physical,&qn,NULL);VkQueueFamilyProperties*qs=malloc(qn*sizeof(*qs));vkGetPhysicalDeviceQueueFamilyProperties(physical,&qn,qs);uint32_t q=0;while(q<qn&&!(qs[q].queueFlags&VK_QUEUE_GRAPHICS_BIT))q++;free(qs);if(q==qn)return 1;float priority=1;VkDeviceQueueCreateInfo qi={.sType=VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,.queueFamilyIndex=q,.queueCount=1,.pQueuePriorities=&priority};VkPhysicalDeviceFeatures features;vkGetPhysicalDeviceFeatures(physical,&features);VkDeviceCreateInfo dci={.sType=VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,.queueCreateInfoCount=1,.pQueueCreateInfos=&qi,.pEnabledFeatures=&features};CHECK(vkCreateDevice(physical,&dci,NULL,&device));VkQueue queue;vkGetDeviceQueue(device,q,0,&queue);
 Buffer positions=buffer(9*16,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT),materials=buffer(3*28*4,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT),camera=buffer(208,VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT),field=buffer(256,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT),shadow=buffer(80,VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT),surface_cache=buffer(64+9*8*4,VK_BUFFER_USAGE_STORAGE_BUFFER_BIT);
 float *p=positions.data,*m=materials.data,*c=camera.data;for(int t=0;t<3;t++){float z=t==0?-4:t==1?-2:-3;float xyz[]={-2,-2,z,2,-2,z,0,2,z};for(int v=0;v<3;v++){memcpy(p+(t*3+v)*4,xyz+v*3,12);((uint32_t*)p)[(t*3+v)*4+3]=t;}int row=t*28;m[row]=t==0?.6f:.2f;m[row+1]=t==0?.1f:.4f;m[row+2]=t==0?.1f:.6f;m[row+3]=1;m[row+6]=1;m[row+20]=1;if(shadow_case&&strcmp(argv[3],"metal")==0)m[row+21]=1;if(t==1){m[row+14]=1;m[row+15]=1;}m[row+27]=1;}
 for(int base=0;base<=16;base+=16){c[base]=1;c[base+5]=1;c[base+11]=-1;c[base+14]=.05f;}c[36]=W;c[37]=H;c[38]=.25f;c[39]=-.375f;c[8]=2*c[38]/W;c[9]=2*c[39]/H;c[42]=1;c[43]=3.14159265359f;c[44]=c[45]=c[46]=1;
 uint32_t* cache=surface_cache.data;cache[0]=9;cache[1]=7;cache[2]=16;cache[5]=1;
 for(int vertex=0;vertex<9;vertex++){int row=16+vertex*8;cache[row]=7;cache[row+1]=1;for(int channel=0;channel<3;channel++){float factor=shadow_case&&strcmp(argv[3],"blocker")==0?0:shadow_case&&strcmp(argv[3],"colored")==0?(channel==0?.5f:channel==1?.25f:.1f):1;float value=3.14159265f*factor;memcpy(cache+row+4+channel,&value,4);}}
 if(shadow_case&&strcmp(argv[3],"view")==0){float cs=cosf(.25f),sn=sinf(.25f),eye=.5f;c[48]=eye;
 for(int base=0;base<=16;base+=16){c[base]=cs;c[base+1]=0;c[base+3]=-sn;c[base+8]=-sn;c[base+9]=0;c[base+11]=-cs;c[base+12]=-cs*eye;c[base+13]=0;c[base+15]=sn*eye;}
 for(int col=0;col<4;col++){c[col*4]-=2*c[38]/W*c[col*4+3];c[col*4+1]-=2*c[39]/H*c[col*4+3];}}
 VkFormat formats[]={VK_FORMAT_R16G16B16A16_SFLOAT,VK_FORMAT_R32_SFLOAT,VK_FORMAT_R16G16_SFLOAT,VK_FORMAT_R16G16B16A16_SFLOAT,VK_FORMAT_R16G16B16A16_SFLOAT,VK_FORMAT_R32G32B32A32_SFLOAT,VK_FORMAT_D32_SFLOAT};Image targets[7];for(int i=0;i<7;i++)targets[i]=image(formats[i],i==6,0);Image atlas=image(VK_FORMAT_R8G8B8A8_UNORM,0,1);Image shadow_texture=image(VK_FORMAT_R32_SFLOAT,0,0);
 Buffer shadow_pixels=buffer(W*H*4,VK_BUFFER_USAGE_TRANSFER_SRC_BIT);float*light=shadow.data;
 // Plane z_light=.5+.05*x-.035*y, sampled at nearest shadow texel centers.
 light[0]=.5f;light[5]=.5f;light[2]=.05f;light[6]=-.035f;light[14]=.5f;light[15]=1;light[16]=shadow_case?1:0;light[17]=.00005f;
 for(int y=0;y<H;y++)for(int x=0;x<W;x++)((float*)shadow_pixels.data)[y*W+x]=.5f+.05f*((x+.5f)/W*4-2)-.035f*((y+.5f)/H*4-2)-(shadow_case&&strcmp(argv[3],"blocker")==0?.1f:0);
VkSamplerCreateInfo sci={.sType=VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,.magFilter=VK_FILTER_NEAREST,.minFilter=VK_FILTER_NEAREST,.mipmapMode=VK_SAMPLER_MIPMAP_MODE_NEAREST,.addressModeU=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,.addressModeV=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,.addressModeW=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE};VkSampler sampler;CHECK(vkCreateSampler(device,&sci,NULL,&sampler));
 VkDescriptorSetLayoutBinding bindings[10];uint32_t ids[]={0,1,2,3,4,5,6,7,8,9};for(int i=0;i<10;i++){int id=ids[i];bindings[i]=(VkDescriptorSetLayoutBinding){.binding=id,.descriptorCount=1,.descriptorType=id==2||id==9?VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER:(id==4||id==7||id==8?VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER),.stageFlags=VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT};}VkDescriptorSetLayoutCreateInfo slci={.sType=VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,.bindingCount=10,.pBindings=bindings};VkDescriptorSetLayout set_layout;CHECK(vkCreateDescriptorSetLayout(device,&slci,NULL,&set_layout));VkDescriptorPoolSize sizes[]={{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,5},{VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,2},{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,3}};VkDescriptorPoolCreateInfo dpci={.sType=VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,.maxSets=1,.poolSizeCount=3,.pPoolSizes=sizes};VkDescriptorPool descriptor_pool;CHECK(vkCreateDescriptorPool(device,&dpci,NULL,&descriptor_pool));VkDescriptorSetAllocateInfo sai={.sType=VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,.descriptorPool=descriptor_pool,.descriptorSetCount=1,.pSetLayouts=&set_layout};VkDescriptorSet set;CHECK(vkAllocateDescriptorSets(device,&sai,&set));
 Buffer buffers[]={positions,materials,camera,field,positions,shadow,surface_cache};uint32_t buffer_bindings[]={0,1,2,3,5,9,6};VkDescriptorBufferInfo bi[7];VkWriteDescriptorSet writes[10];for(int i=0;i<7;i++){bi[i]=(VkDescriptorBufferInfo){buffers[i].buffer,0,buffers[i].size};writes[i]=(VkWriteDescriptorSet){.sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,.dstSet=set,.dstBinding=buffer_bindings[i],.descriptorCount=1,.descriptorType=i==2||i==5?VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,.pBufferInfo=&bi[i]};}VkDescriptorImageInfo ii[3];for(int i=0;i<3;i++)ii[i]=(VkDescriptorImageInfo){.sampler=sampler,.imageView=i==0?atlas.view:shadow_texture.view,.imageLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};int image_bindings[]={4,7,8};for(int i=0;i<3;i++)writes[7+i]=(VkWriteDescriptorSet){.sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,.dstSet=set,.dstBinding=image_bindings[i],.descriptorCount=1,.descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,.pImageInfo=&ii[i]};vkUpdateDescriptorSets(device,10,writes,0,NULL);
 VkAttachmentDescription attachments[7];VkAttachmentReference refs[6];VkImageView views[7];for(int i=0;i<7;i++){attachments[i]=(VkAttachmentDescription){.format=formats[i],.samples=VK_SAMPLE_COUNT_1_BIT,.loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR,.storeOp=VK_ATTACHMENT_STORE_OP_STORE,.stencilLoadOp=VK_ATTACHMENT_LOAD_OP_DONT_CARE,.stencilStoreOp=VK_ATTACHMENT_STORE_OP_DONT_CARE,.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED,.finalLayout=i==6?VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL:VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL};if(i<6)refs[i]=(VkAttachmentReference){i,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};views[i]=targets[i].view;}VkAttachmentReference dr={6,VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};VkSubpassDescription subpass={.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS,.colorAttachmentCount=6,.pColorAttachments=refs,.pDepthStencilAttachment=&dr};VkSubpassDependency dep={.srcSubpass=0,.dstSubpass=VK_SUBPASS_EXTERNAL,.srcStageMask=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,.dstStageMask=VK_PIPELINE_STAGE_TRANSFER_BIT,.srcAccessMask=VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,.dstAccessMask=VK_ACCESS_TRANSFER_READ_BIT};VkRenderPassCreateInfo rpci={.sType=VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO,.attachmentCount=7,.pAttachments=attachments,.subpassCount=1,.pSubpasses=&subpass,.dependencyCount=1,.pDependencies=&dep};VkRenderPass renderpass;CHECK(vkCreateRenderPass(device,&rpci,NULL,&renderpass));VkFramebufferCreateInfo fbci={.sType=VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,.renderPass=renderpass,.attachmentCount=7,.pAttachments=views,.width=W,.height=H,.layers=1};VkFramebuffer framebuffer;CHECK(vkCreateFramebuffer(device,&fbci,NULL,&framebuffer));VkPushConstantRange range={.stageFlags=VK_SHADER_STAGE_VERTEX_BIT,.size=4};VkPipelineLayoutCreateInfo plci={.sType=VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,.setLayoutCount=1,.pSetLayouts=&set_layout,.pushConstantRangeCount=1,.pPushConstantRanges=&range};VkPipelineLayout pipeline_layout;CHECK(vkCreatePipelineLayout(device,&plci,NULL,&pipeline_layout));VkShaderModule vs=shader(argv[1]),fs=shader(argv[2]);VkPipelineShaderStageCreateInfo stages[]={{.sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,.stage=VK_SHADER_STAGE_VERTEX_BIT,.module=vs,.pName="main"},{.sType=VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,.stage=VK_SHADER_STAGE_FRAGMENT_BIT,.module=fs,.pName="main"}};
 VkPipelineVertexInputStateCreateInfo vi={.sType=VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};VkPipelineInputAssemblyStateCreateInfo ia={.sType=VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,.topology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST};VkViewport viewport={0,0,W,H,0,1};VkRect2D rect={{0,0},{W,H}};VkPipelineViewportStateCreateInfo vp={.sType=VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,.viewportCount=1,.pViewports=&viewport,.scissorCount=1,.pScissors=&rect};VkPipelineRasterizationStateCreateInfo rs={.sType=VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,.polygonMode=VK_POLYGON_MODE_FILL,.cullMode=VK_CULL_MODE_NONE,.frontFace=VK_FRONT_FACE_CLOCKWISE,.lineWidth=1};VkPipelineMultisampleStateCreateInfo ms={.sType=VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,.rasterizationSamples=VK_SAMPLE_COUNT_1_BIT};VkPipelineDepthStencilStateCreateInfo ds={.sType=VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO,.depthTestEnable=VK_TRUE,.depthWriteEnable=VK_TRUE,.depthCompareOp=VK_COMPARE_OP_GREATER};VkPipelineColorBlendAttachmentState ba[6];memset(ba,0,sizeof(ba));for(int i=0;i<6;i++)ba[i].colorWriteMask=15;VkPipelineColorBlendStateCreateInfo bs={.sType=VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,.attachmentCount=6,.pAttachments=ba};VkGraphicsPipelineCreateInfo gpci={.sType=VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,.stageCount=2,.pStages=stages,.pVertexInputState=&vi,.pInputAssemblyState=&ia,.pViewportState=&vp,.pRasterizationState=&rs,.pMultisampleState=&ms,.pDepthStencilState=&ds,.pColorBlendState=&bs,.layout=pipeline_layout,.renderPass=renderpass};VkPipeline pipeline;CHECK(vkCreateGraphicsPipelines(device,0,1,&gpci,NULL,&pipeline));
 VkCommandPoolCreateInfo cpci={.sType=VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,.queueFamilyIndex=q};VkCommandPool command_pool;CHECK(vkCreateCommandPool(device,&cpci,NULL,&command_pool));VkCommandBufferAllocateInfo cai={.sType=VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,.commandPool=command_pool,.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY,.commandBufferCount=1};VkCommandBuffer cmd;CHECK(vkAllocateCommandBuffers(device,&cai,&cmd));VkCommandBufferBeginInfo begin={.sType=VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};CHECK(vkBeginCommandBuffer(cmd,&begin));VkImageMemoryBarrier ib={.sType=VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,.oldLayout=VK_IMAGE_LAYOUT_UNDEFINED,.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT,.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED,.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED,.image=atlas.image,.subresourceRange={.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT,.levelCount=1,.layerCount=1}};vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,NULL,0,NULL,1,&ib);VkClearColorValue white={{1,1,1,0}};vkCmdClearColorImage(cmd,atlas.image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,&white,1,&ib.subresourceRange);ib.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;ib.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;ib.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;ib.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,NULL,0,NULL,1,&ib);
 ib.image=shadow_texture.image;ib.oldLayout=VK_IMAGE_LAYOUT_UNDEFINED;ib.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;ib.srcAccessMask=0;ib.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,NULL,0,NULL,1,&ib);
 VkBufferImageCopy shadow_copy={.imageSubresource={.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT,.layerCount=1},.imageExtent={W,H,1}};vkCmdCopyBufferToImage(cmd,shadow_pixels.buffer,shadow_texture.image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&shadow_copy);
 ib.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;ib.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;ib.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;ib.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,NULL,0,NULL,1,&ib);
 VkClearValue clear[7];memset(clear,0,sizeof(clear));VkRenderPassBeginInfo rb={.sType=VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,.renderPass=renderpass,.framebuffer=framebuffer,.renderArea=rect,.clearValueCount=7,.pClearValues=clear};vkCmdBeginRenderPass(cmd,&rb,VK_SUBPASS_CONTENTS_INLINE);vkCmdBindPipeline(cmd,VK_PIPELINE_BIND_POINT_GRAPHICS,pipeline);vkCmdBindDescriptorSets(cmd,VK_PIPELINE_BIND_POINT_GRAPHICS,pipeline_layout,0,1,&set,0,NULL);uint32_t surface_base=0;vkCmdPushConstants(cmd,pipeline_layout,VK_SHADER_STAGE_VERTEX_BIT,0,4,&surface_base);vkCmdDraw(cmd,9,1,0,0);vkCmdEndRenderPass(cmd);
 int byte_sizes[]={8,4,4,8,8,16};Buffer readbacks[6];for(int i=0;i<6;i++){readbacks[i]=buffer(W*H*byte_sizes[i],VK_BUFFER_USAGE_TRANSFER_DST_BIT);VkBufferImageCopy copy={.imageSubresource={.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT,.layerCount=1},.imageExtent={W,H,1}};vkCmdCopyImageToBuffer(cmd,targets[i].image,VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,readbacks[i].buffer,1,&copy);}VkMemoryBarrier ready={.sType=VK_STRUCTURE_TYPE_MEMORY_BARRIER,.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT,.dstAccessMask=VK_ACCESS_HOST_READ_BIT};vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_HOST_BIT,0,1,&ready,0,NULL,0,NULL);CHECK(vkEndCommandBuffer(cmd));VkSubmitInfo submit={.sType=VK_STRUCTURE_TYPE_SUBMIT_INFO,.commandBufferCount=1,.pCommandBuffers=&cmd};CHECK(vkQueueSubmit(queue,1,&submit,VK_NULL_HANDLE));CHECK(vkQueueWaitIdle(queue));
 if(shadow_case){int tested=0;for(int y=0;y<H;y++)for(int x=0;x<W;x++){int index=y*W+x;float*pos=(float*)readbacks[5].data+index*4;if(pos[3]!=1||fabsf(pos[2]+3)>1e-5)continue;uint16_t*pixel=(uint16_t*)readbacks[0].data+index*4;float nv=-pos[2]/sqrtf((pos[0]-c[48])*(pos[0]-c[48])+pos[1]*pos[1]+pos[2]*pos[2]);float expected=expected_color(.2f,nv,0,argv[3]);if(fabsf(from_half(pixel[0])-expected)>.002f){fprintf(stderr,"Shadow plane falsely occluded at (%d,%d): color=%f expected=%f\n",x,y,from_half(pixel[0]),expected);return 1;}tested++;}if(tested<10)return 1;printf("PASS: shadow %s (%d plane pixels)\n",argv[3],tested);}
 // Actual graphics pixels above/below the center must match RT's +up image rows.
 for(int y=7;y<=10;y++){float *pos=(float*)readbacks[5].data+(y*W+8)*4;float view_z=c[19]*pos[0]+c[23]*pos[1]+c[27]*pos[2]+c[31];float expected_y=((y+.5f+c[39])/H*2-1)*view_z;if(pos[3]!=1||fabsf(pos[1]-expected_y)>5e-4){fprintf(stderr,"RT image Y mismatch row=%d actual=%f expected=%f\n",y,pos[1],expected_y);return 1;}uint16_t* mv=(uint16_t*)readbacks[2].data+(y*W+8)*2;if(fabsf(from_half(mv[0]))>1e-4||fabsf(from_half(mv[1]))>1e-4){fprintf(stderr,"Static jitter produces motion at row %d\n",y);return 1;}}
 int center=8*W+8;float*world=(float*)readbacks[5].data+center*4;float view_z=c[19]*world[0]+c[23]*world[1]+c[27]*world[2]+c[31];float depth=((float*)readbacks[1].data)[center];if(fabsf(depth-.05f/view_z)>1e-6){fprintf(stderr,"depth %.9f expected %.9f\n",depth,.05f/3);return 1;}if(fabsf(world[2]+3)>1e-5||world[3]!=1){fprintf(stderr,"position %f %f\n",world[2],world[3]);return 1;}uint16_t*albedo=(uint16_t*)readbacks[4].data+center*4;float expected[]={.2f,.4f,.6f};for(int i=0;i<3;i++)if(fabsf(from_half(albedo[i])-expected[i])>.001){fprintf(stderr,"albedo %d %.6f\n",i,from_half(albedo[i]));return 1;}uint16_t*motion=(uint16_t*)readbacks[2].data+center*2;if(fabsf(from_half(motion[0]))>1e-4||fabsf(from_half(motion[1]))>1e-4){fprintf(stderr,"motion %.6f %.6f\n",from_half(motion[0]),from_half(motion[1]));return 1;}uint16_t*color=(uint16_t*)readbacks[0].data+center*4;for(int i=0;i<3;i++){float nv=-world[2]/sqrtf((world[0]-c[48])*(world[0]-c[48])+world[1]*world[1]+world[2]*world[2]);float target=expected_color(expected[i],nv,i,shadow_case?argv[3]:"");if(fabsf(from_half(color[i])-target)>.002){fprintf(stderr,"color %d %.6f target %.6f\n",i,from_half(color[i]),target);return 1;}}
 printf("PASS: actual graphics pipeline, 3 triangles, alpha rejection, reversed depth, material, position, RT image row orientation, zero jittered motion, cached RT sun/GI color and GGX highlight\n");for(int i=0;i<6;i++)free_buffer(readbacks[i]);vkDestroyCommandPool(device,command_pool,NULL);vkDestroyPipeline(device,pipeline,NULL);vkDestroyShaderModule(device,vs,NULL);vkDestroyShaderModule(device,fs,NULL);vkDestroyPipelineLayout(device,pipeline_layout,NULL);vkDestroyFramebuffer(device,framebuffer,NULL);vkDestroyRenderPass(device,renderpass,NULL);vkDestroyDescriptorPool(device,descriptor_pool,NULL);vkDestroyDescriptorSetLayout(device,set_layout,NULL);vkDestroySampler(device,sampler,NULL);free_image(atlas);free_image(shadow_texture);free_buffer(shadow_pixels);for(int i=0;i<7;i++)free_image(targets[i]);free_buffer(positions);free_buffer(materials);free_buffer(camera);free_buffer(field);free_buffer(shadow);free_buffer(surface_cache);vkDestroyDevice(device,NULL);vkDestroyInstance(instance,NULL);return 0;
}
